org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10808
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808
systemProp.java.net.useSystemProxies=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.226
loader_version_range=[1,)
sable_version_range=[2.0.0,)
simulated_version_range=[1.3.0,)
sable_api_version=2.0.3
simulated_api_version=1.3.0

mod_id=aeronautics_utility_objects
artifact_id=create_aeronautics_transmission_linkage
mod_name=Create Aeronautics: Transmission & Linkage
mod_license=CC-BY-NC-4.0
mod_version=0.2.8
mod_group_id=com.enxv.aerouniversaljoint
mod_authors=enxv233
mod_description=Adds universal joints, hydraulic links and kinetic converters for connecting and transmitting motion between Aeronautics structures.
